name = "JuliaForMatlabUsers"
uuid = "f86e1dd0-7c94-40f8-8432-ef2e3e0e511e"
authors = ["Yasri Yudhistira <yyudhistira@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
